apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.admin.name }}
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app: {{ .Values.services.admin.name }}

spec:
  type: ClusterIP

  selector:
    app: {{ .Values.services.admin.name }}

  ports:
    - name: http
      port: {{ .Values.services.admin.port }}
      targetPort: http
      protocol: TCP