apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "streamingapp.fullname" . }}-config
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}

data:
  AWS_REGION: "us-east-1"

  AUTH_SERVICE_URL: "http://auth:3001"
  STREAMING_SERVICE_URL: "http://streaming:3002"
  ADMIN_SERVICE_URL: "http://admin:3003"
  CHAT_SERVICE_URL: "http://chat:3004"

  CLIENT_URLS: "http://{{ .Values.ingress.host }}"

  AWS_S3_BUCKET: "CHANGE_ME"

  AWS_CDN_URL: ""

  STREAMING_PUBLIC_URL: "http://{{ .Values.ingress.host }}/api/streaming"