apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamingapp.fullname" . }}-secret
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME"
  MONGO_URI: "mongodb+srv://sadiksyed247_db_user:<PASSWORD>@cluster0.chanfxo.mongodb.net/streamingapp"
  AWS_ACCESS_KEY_ID: "CHANGE_ME"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"